### ISSUE TITLE
Potions not saved properly

### ISSUE THREAD

**Issue by MegaNarwhal** [RealizedMC/Duels#1]
When a potion is saved in a kit, it loses its potion effect.

**Comment by RealizedMC** [comment]
Are you using 1.9?

**Comment by MegaNarwhal** [comment]
I'm using the latest version of Spigot (git-Spigot-e6f93f4-935f18b). The problem only occurs after the server has been restarted. I've looked in kits.json and the type of potion is not recorded.

**Comment by RealizedMC** [comment]
I found a solution, 1.0.8 will patch the issue. I'll close this when I update the resource on SpigotMC. Thanks

**Comment by MegaNarwhal** [comment]
Thank you :+1:

**Comment by RealizedMC** [comment]
Oops, didn't mean to close it yet xD

**Comment by RealizedMC** [comment]
1.0.8 is released. Issue is now closed.
