### ISSUE TITLE
Change the interface name (in api)

### ISSUE THREAD

**Issue by tomocrafter** [RealizedMC/Duels#6]
You should change the duels-api's interfaces name.
because when implement the that interface,
class name will be like
`public class Arena extends BaseButton implements me.realized.duels.api.arena.Arena { `
so, this is the so long, if you change the interface for example, when Arena to IArena, you can write like this
`public class Arena extends BaseButton implements IArena {`

I'm so sorry for my bad English because I'm Japanese and I didn't use any translators.

**Comment by RealizedMC** [comment]
I prefer using the convention the interfaces in JDK are using. (Example being [List](https://docs.oracle.com/javase/8/docs/api/java/util/List.html))

Also, since API module can be compiled on its own as of v3.0.0, there shouldn't be a problem with duplicate names.
